services:
  - type: web
    name: sleeper-mcp
    runtime: python
    plan: free
    buildCommand: "pip install uv && uv sync"
    startCommand: "uv run python build_cache.py; uv run python sleeper_mcp.py http"
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.13"
      - key: SLEEPER_LEAGUE_ID
        value: "1315471209655181312"
      - key: SLEEPER_USER_ID
        value: "1047750466941300736"
      - key: SLEEPER_LEAGUES
        value: '{"degenerate":"1389884072729260032","chopdeez":"1389693534050721792","replacements":"1382500594995953664","tejas":"1315471209655181312"}'
    autoDeploy: true